define({
  root: ({
    _widgetLabel: "Social Widget",
    social: "Twitter",
    search: "Search",
    query: "Query",
    until: "Until",
    density: "Density",
    densityMessage: "Higher the value, greater the number of elements on the map will be",
    logout: "Logout",
    signin: "Signin",
    account: "Account",
	until0: "Today",
	until1: "Yesterday",
	until2: "2 days ago",
	until3: "3 days ago",
	until4: "4 days ago",
	until5: "5 days ago",
	until6: "6 days ago",
	until7: "7 days ago"
    
	
  }),  
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 1,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 1,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0  
});
